export const portalPage=`<!doctype html><html lang="es"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Órbita · Administración de agentes</title><style>
:root{font-family:system-ui,sans-serif;color:#242439;background:#f6f5fa}*{box-sizing:border-box}body{margin:0}header{background:#fff;border-bottom:1px solid #e5e1ee;padding:22px 6%;display:flex;justify-content:space-between;align-items:center}h1{font-size:26px;margin:0;letter-spacing:-1px}header small{color:#77718a}main{max-width:1200px;margin:30px auto;padding:0 24px}h2{font-size:20px}h3{margin-top:0}.card{background:white;border:1px solid #e5e1ee;border-radius:16px;padding:24px;box-shadow:0 4px 18px #25213b05}#signin{max-width:470px;margin:80px auto}.grid{display:grid;grid-template-columns:340px 1fr;gap:24px}label{display:block;margin:16px 0 7px;font-size:14px;font-weight:600}input,select,textarea{width:100%;padding:12px;border:1px solid #d5cfe0;border-radius:8px;font:inherit}button{padding:11px 17px;border-radius:9px;border:1px solid #d6cee5;background:white;color:#4f347a;font:inherit;font-weight:600;cursor:pointer}button.primary{background:#62409b;color:white;border-color:#62409b}button:disabled{opacity:.55;cursor:wait}.row{display:flex;gap:12px;align-items:center;flex-wrap:wrap}.muted{color:#77718a;font-size:14px}.badge{display:inline-block;border-radius:20px;padding:5px 10px;background:#eee7f8;color:#684199;font-size:12px}.request{display:block;width:100%;text-align:left;margin:10px 0;padding:16px}.request strong{display:block;color:#242439}.request small{display:block;margin:6px 0;color:#77718a}.request.active{border-color:#62409b;background:#f7f2ff}dl{display:grid;grid-template-columns:1fr 1fr;gap:12px}dt{font-size:14px;color:#77718a}dd{margin:4px 0;font-weight:600}.total{font-size:28px;color:#62409b;border-top:1px solid #eee;padding-top:18px}label.check{display:flex;gap:10px;align-items:flex-start;font-weight:400}label.check input{width:auto;margin-top:4px}.notice{white-space:pre-wrap;color:#8b351b;background:#fff1e8;border-radius:9px;padding:12px}.notice:empty{display:none}.bubble{padding:15px;border-radius:12px;background:#f1eef6;margin:12px 0;white-space:pre-wrap;overflow-wrap:anywhere}.bubble.reply{background:#edf5ef}.empty{padding:30px 0;color:#77718a}footer{margin-top:35px;color:#77718a;font-size:13px}[hidden]{display:none!important}@media(max-width:760px){.grid{grid-template-columns:1fr}main{padding:0 14px}dl{grid-template-columns:1fr}header{padding:20px}}
</style></head><body><header><div><h1>Órbita</h1><small>Alba Vision · Administración de agentes</small></div><div class="row"><span id="who" class="muted"></span><button id="logout" hidden>Salir</button></div></header><main>
<section id="signin" class="card"><h2>Acceso del responsable</h2><p class="muted">Administra tus agentes y consulta su uso disponible.</p><form id="login"><label for="account">Cuenta</label><input id="account" autocomplete="username" required maxlength="40"><label for="code">Código de acceso</label><input id="code" type="password" autocomplete="current-password" required minlength="32" maxlength="256"><button class="primary" style="margin-top:20px">Entrar</button></form><p id="loginNotice" class="notice" role="alert"></p></section>
<section id="workspace" hidden><div class="row" style="justify-content:space-between;margin-bottom:24px"><div><h2>Agentes y clientes</h2><p class="muted" id="scopeNote"></p></div><button id="refresh">Actualizar</button></div><p id="notice" class="notice" role="alert"></p><section id="management"></section><section id="newClient" class="card" hidden style="margin:24px 0"><h3>Agregar cliente</h3><form id="clientForm"><div class="row"><div><label for="clientName">Nombre del negocio</label><input id="clientName" required maxlength="80"></div><div><label for="clientSlug">Identificador</label><input id="clientSlug" required pattern="[a-z0-9][a-z0-9_-]{0,39}" maxlength="40"></div><div><label for="clientBudget">Límite mensual Jev (USD)</label><input id="clientBudget" type="number" min="0" max="1000000" step="0.00000001" placeholder="Sin límite asignado"></div></div><p class="muted">Se crea pausado. La conexión de WhatsApp y el acceso del cliente se configuran por separado.</p><button class="primary">Crear cliente</button></form></section><div class="row" style="margin:24px 0"><h2>Conversaciones y solicitudes</h2><label for="tenantSelect">Cliente</label><select id="tenantSelect" style="max-width:320px"></select></div><div class="grid"><aside class="card"><h3>Últimas solicitudes</h3><div id="queue"></div><h3>Conversaciones</h3><div id="inbox"></div></aside><section id="detail" class="card"><p class="empty">Selecciona una solicitud o conversación para revisar sus datos.</p></section></div></section>
<footer>Órbita es una herramienta de Alba Vision. Cada negocio conserva su propia operación.</footer></main><script>
const root='/orbita/panel';let csrf='',requests=[],selected=null,commerceEnabled=false,accountRole='tenant',tenantId=null,summary=null;
const el=id=>document.getElementById(id),fmt=n=>new Intl.NumberFormat('es-MX',{style:'currency',currency:'MXN'}).format(n),labels={pending:'Pendiente de revisión',committing:'Revisión en proceso',confirmed:'Pedido confirmado',cancelled:'Cancelada',uncertain:'Requiere reconciliación'};
async function api(path,method='GET',body){const r=await fetch(root+path+(tenantId&&path!=='/session'&&path!=='/logout'&&path!=='/agents'&&path!=='/clients'?(path.includes('?')?'&':'?')+'tenant='+encodeURIComponent(tenantId):''),{method,headers:method==='POST'?{'Content-Type':'application/json','X-Orbita-CSRF':csrf}:{},body:body===undefined?undefined:JSON.stringify(body)});const data=await r.json();if(!r.ok)throw new Error(data.message||data.error||'No se pudo completar la operación.');return data}
function node(tag,text,cls){const n=document.createElement(tag);if(text!==undefined)n.textContent=text;if(cls)n.className=cls;return n}
function session(s){csrf=s.csrf;accountRole=s.role||'tenant';tenantId=s.tenantId;el('newClient').hidden=accountRole!=='admin';el('scopeNote').textContent=accountRole==='admin'?'Control central de Alba Vision. Selecciona un cliente para atender su operación.':'Solo puedes administrar el agente de tu negocio. Los límites los asigna Alba Vision.';commerceEnabled=s.commerceEnabled===true;el('notice').textContent=commerceEnabled?'':'Las conversaciones están disponibles. La creación de pedidos está pendiente de activar.';el('who').textContent=s.name;el('signin').hidden=true;el('workspace').hidden=false;el('logout').hidden=false}
async function refresh(){requests=(await api('/requests')).requests;const queue=el('queue');queue.replaceChildren();if(!requests.length)queue.append(node('p','Todavía no hay solicitudes.','empty'));for(const r of requests){const b=node('button',undefined,'request'+(r.id===selected?' active':''));b.append(node('strong',r.body.input.customerName),node('small',r.body.quote.menuName+' · '+r.body.input.quantity+' paquete(s)'),node('span',labels[r.status]||r.status,'badge'));b.onclick=()=>{selected=r.id;render(r);refreshQueue()};queue.append(b)}if(selected){const r=requests.find(r=>r.id===selected);if(r)render(r)}}
function refreshQueue(){for(const [i,b] of [...el('queue').querySelectorAll('button')].entries())b.className='request'+(requests[i].id===selected?' active':'')}
async function inbox(){const rows=(await api('/inbox')).conversations,list=el('inbox');list.replaceChildren();for(const row of rows){const b=node('button',undefined,'request');b.append(node('strong',row.message.name||row.message.from),node('small',row.held?'Agente pausado':row.needsHuman?'Requiere atención':'Agente activo'));b.onclick=()=>conversation(row);list.append(b)}}
async function conversation(row){selected=null;refreshQueue();const d=el('detail');d.replaceChildren(node('h2',row.message.name||'Conversación'),node('p',row.message.from,'muted'));const result=await api('/conversations?channel='+encodeURIComponent(row.channelId)+'&sender='+encodeURIComponent(row.message.from));const held=result.messages[0]?.held||false;const toggle=node('button',held?'Reanudar agente':'Pausar agente');toggle.onclick=async()=>{await api('/hold','POST',{channelId:row.channelId,sender:row.message.from,held:!held});await conversation(row);await inbox()};d.append(toggle,node('p','Para responder personalmente, usa el WhatsApp Business del negocio con el agente pausado.','muted'));for(const m of result.messages.reverse()){d.append(node('p',new Date(m.message.receivedAt).toLocaleString('es-MX'),'muted'),node('div',(m.direction==='business'?'Equipo · ':'')+(m.message.body||'Archivo recibido'),m.direction==='business'?'bubble reply':'bubble'));if(m.reply)d.append(node('div',m.reply,'bubble reply'))}}
function render(r){const d=el('detail'),input=r.body.input,q=r.body.quote;d.replaceChildren();d.append(node('h2',input.customerName),node('span',labels[r.status]||r.status,'badge'),node('p',input.customerPhone,'muted'));const dl=node('dl');for(const [k,v] of [['Menú',q.menuName],['Cantidad',input.quantity],['Entrega',input.fulfillment==='pickup'?'Recogida en sucursal':input.address+' · CP '+input.postalCode],['Subtotal',fmt(q.subtotalMxn)],['Extras',fmt(q.extrasMxn)],['Envío',fmt(q.deliveryMxn)],['Descuento',fmt(q.discountMxn)],['Referencia',r.id.slice(0,8)]]){const wrap=node('div');wrap.append(node('dt',k),node('dd',v));dl.append(wrap)}d.append(dl,node('p',fmt(q.totalMxn),'total'));if(r.orderId)d.append(node('p','Pedido: '+r.orderId));
if(!q.customerVerified)d.append(node('p','El teléfono no está vinculado a un cliente único de Sankalpa. Registra o verifica su perfil en el sistema del negocio antes de confirmar.','notice'));
const conversations=node('button','Ver conversación');conversations.onclick=async()=>{const result=await api('/conversations?channel='+encodeURIComponent(r.channelId)+'&sender='+encodeURIComponent(input.customerPhone));const existing=d.querySelector('[data-messages]');if(existing)existing.remove();const list=node('div');list.dataset.messages='true';const messages=result.messages.filter(m=>m.message.from===input.customerPhone);for(const m of messages.reverse()){list.append(node('p',m.message.name+' · '+new Date(m.message.receivedAt).toLocaleString('es-MX'),'muted'),node('div',(m.direction==='business'?'Equipo · ':'')+(m.message.body||'Archivo recibido'),m.direction==='business'?'bubble reply':'bubble'));if(m.reply)list.append(node('div',m.reply,'bubble reply'))}const held=messages.at(-1)?.held||false;const toggle=node('button',held?'Reanudar agente':'Pausar agente');toggle.onclick=async()=>{await api('/hold','POST',{channelId:r.channelId,sender:input.customerPhone,held:!held});conversations.click()};list.prepend(toggle);d.append(list)};d.append(conversations);
if(commerceEnabled&&['pending','uncertain','committing'].includes(r.status)){const form=node('form');const methodLabel=node('label','Método de pago elegido'),method=node('select');for(const [value,text] of [['transferencia','Transferencia verificada'],['efectivo','Efectivo al recibir, autorizado']]){if(value!==input.paymentMethod)continue;const o=node('option',text);o.value=value;method.append(o)}method.id='reviewMethod';methodLabel.htmlFor=method.id;const proofLabel=node('label','Referencia o nota de revisión'),proof=node('input');proof.id='reviewProof';proofLabel.htmlFor=proof.id;proof.required=true;proof.minLength=3;proof.maxLength=200;const inv=node('input'),pay=node('input');inv.type=pay.type='checkbox';inv.required=pay.required=true;const invLabel=node('label',undefined,'check'),payLabel=node('label',undefined,'check');invLabel.append(inv,node('span','Revisé disponibilidad, dirección y condiciones de entrega.'));payLabel.append(pay,node('span','Verifiqué el pago o autoricé cobrar efectivo al recibir.'));const buttons=node('div',undefined,'row'),approve=node('button',r.status==='pending'?'Confirmar pedido':'Reconciliar la misma operación','primary');approve.type='submit';approve.disabled=!q.customerVerified;buttons.append(approve);if(r.status==='pending'){const cancel=node('button','Cancelar solicitud');cancel.type='button';cancel.onclick=async()=>{cancel.disabled=true;try{await api('/cancel','POST',{id:r.id,revision:r.revision});await refresh()}catch(e){el('notice').textContent=e.message;cancel.disabled=false}};buttons.append(cancel)}form.append(methodLabel,method,proofLabel,proof,invLabel,payLabel,buttons);form.onsubmit=async e=>{e.preventDefault();approve.disabled=true;el('notice').textContent='';try{await api('/approve','POST',{id:r.id,revision:r.revision,inventoryReviewed:inv.checked,paymentReviewed:pay.checked,paymentMethod:method.value,paymentReference:proof.value});await refresh()}catch(e){el('notice').textContent=e.message;await refresh()}};d.append(form)} }

const usd=n=>n===null?'Sin límite asignado':new Intl.NumberFormat('es-MX',{style:'currency',currency:'USD',minimumFractionDigits:4,maximumFractionDigits:8}).format(n);
async function act(path,body){try{await api(path,'POST',body);await loadAgents()}catch(e){el('notice').textContent=e.message}}
async function loadAgents(){summary=await api('/agents');const wrap=el('management');wrap.replaceChildren(node('p','Periodo '+summary.period+' · '+summary.timeZone,'muted'));const selection=el('tenantSelect');selection.replaceChildren();
for(const t of summary.tenants){const option=node('option',t.name);option.value=t.id;selection.append(option)}
if(!summary.tenants.some(t=>t.id===tenantId))tenantId=summary.tenants[0]?.id||null;selection.value=tenantId||'';selection.disabled=accountRole!=='admin';
for(const t of summary.tenants){const card=node('section',undefined,'card');card.style.marginBottom='20px';card.append(node('h3',t.name),node('span',t.paused?'Servicio pausado por Alba Vision':'Servicio habilitado','badge'));const dl=node('dl');
for(const [label,value] of [['Disponible este mes',usd(t.remainingUsd)],['Límite mensual Jev',usd(t.monthlyBudgetUsd)],['Consumo estimado',usd(t.usedUsd)],['Consultas a Jev',t.calls],['Tokens de entrada',t.inputTokens],['Tokens de salida',t.outputTokens]]){const cell=node('div');cell.append(node('dt',label),node('dd',String(value)));dl.append(cell)}card.append(dl);if(t.unverifiedCalls)card.append(node('p',t.unverifiedCalls+' consulta(s) con reserva estimada pendiente de verificación.','muted'));
for(const a of t.agents){const box=node('div');box.style.borderTop='1px solid #eee';box.style.paddingTop='18px';const effective=a.enabled&&!t.paused&&a.credentialsReady;box.append(node('h3','Agente de WhatsApp'),node('p',(effective?'Activo':'Pausado o pendiente de conexión')+' · '+(a.mode==='trial'?'Canal de prueba':'Canal de producción')+' · '+a.model,'muted'),node('p',a.messagesThisMonth+' mensajes este mes · '+(a.jevEnabled?'Jev habilitado':'Atención guiada sin Jev')+(a.mode==='trial'?' · '+a.allowedSenderCount+' remitente(s) autorizado(s)':''),'muted'));
if(!a.credentialsReady||a.needsAttention)box.append(node('p','La conexión requiere revisión de Alba Vision.','notice'));
const toggle=node('button',a.enabled?'Pausar agente':'Reanudar agente');toggle.disabled=!a.enabled&&!a.credentialsReady;toggle.onclick=()=>act('/agent-state',{tenantId:t.id,channelId:a.id,enabled:!a.enabled});box.append(toggle);
if(accountRole==='admin'){const jev=node('button',a.jevEnabled?'Desactivar Jev':'Activar Jev');jev.style.marginLeft='10px';jev.onclick=()=>act('/agent-state',{tenantId:t.id,channelId:a.id,enabled:a.enabled,jevEnabled:!a.jevEnabled});box.append(jev)}card.append(box)}
if(!t.agents.length)card.append(node('p','Todavía no tiene un canal de WhatsApp conectado.','empty'));
if(accountRole==='admin'){const form=node('form'),budget=node('input'),paused=node('input');budget.id='budget-'+t.id;budget.type='number';budget.min='0';budget.max='1000000';budget.step='0.00000001';budget.value=t.monthlyBudgetUsd??'';budget.placeholder='Sin límite asignado';const label=node('label','Límite mensual Jev (USD)');label.htmlFor=budget.id;paused.type='checkbox';paused.checked=t.paused;const hold=node('label',undefined,'check');hold.append(paused,node('span','Pausar todo el servicio de este cliente'));const submit=node('button','Guardar límites','primary');submit.type='submit';form.append(label,budget,hold,submit);form.onsubmit=async e=>{e.preventDefault();submit.disabled=true;await act('/tenant-settings',{tenantId:t.id,budgetUsd:budget.value===''?null:Number(budget.value),paused:paused.checked});submit.disabled=false};card.append(form)}wrap.append(card)}wrap.append(node('p',summary.costBasis+' No representa un paquete comercial de mensajes.','muted'));}
async function update(){await loadAgents();if(tenantId)await Promise.all([refresh(),inbox()]);else{el('queue').replaceChildren();el('inbox').replaceChildren()}}
el('tenantSelect').onchange=async e=>{tenantId=e.target.value;selected=null;el('detail').replaceChildren(node('p','Selecciona una conversación.','empty'));try{await Promise.all([refresh(),inbox()])}catch(error){el('notice').textContent=error.message}};
el('clientForm').onsubmit=async e=>{e.preventDefault();const button=e.target.querySelector('button');button.disabled=true;try{await api('/clients','POST',{name:el('clientName').value,slug:el('clientSlug').value,budgetUsd:el('clientBudget').value===''?null:Number(el('clientBudget').value)});e.target.reset();await update()}catch(error){el('notice').textContent=error.message}finally{button.disabled=false}};

el('login').onsubmit=async e=>{e.preventDefault();const code=el('code');try{const s=await api('/session','POST',{account:el('account').value,code:code.value});code.value='';session(s);await update()}catch(e){code.value='';el('loginNotice').textContent=e.message}};
el('refresh').onclick=()=>update().catch(e=>el('notice').textContent=e.message);el('logout').onclick=async()=>{await api('/logout','POST',{});location.reload()};api('/session').then(async s=>{session(s);await update()}).catch(()=>{});
</script></body></html>`;
